-- Clear existing templates
TRUNCATE TABLE public.ai_templates;

-- Insert 4 Premium Templates for EACH tool (16 total) with Freepik Images
INSERT INTO public.ai_templates (title, description, tool_type, category, difficulty, usage_count, preview_url, is_featured, prompt) VALUES 

-- IMAGE EXAMPLES
('Luxe Skin Serum Ad', 'High-end product photography for skincare marketing. Perfect for Instagram ads.', 'Image', 'Marketing', 'Beginner', 1250, 'https://img.freepik.com/free-photo/luxurious-skincare-product-packaging_23-2150388277.jpg', true, 'A high-end cinematic product shot of a luxury glass serum bottle with organic leaf shadows, soft morning light, 8k resolution, photorealistic'),
('Cyberpunk Samurai', 'Intricate character design of a futuristic warrior. Neon aesthetics and rainy atmosphere.', 'Image', 'Creative', 'Pro', 3100, 'https://img.freepik.com/free-photo/futuristic-samurai-character-design_23-2151044391.jpg', false, 'Detailed portrait of a cyberpunk samurai, glowing neon katanas, rain slicked streets, cinematic lighting, 8k render, octane render style'),
('Corporate Minimalism', 'Clean and professional abstract background for presentations and business branding.', 'Image', 'Business', 'Beginner', 950, 'https://img.freepik.com/free-photo/minimalist-gray-office-interior_23-2149313936.jpg', false, 'Modern minimalist corporate background with soft blue gradients and subtle geometric shapes, high-resolution, clean professional aesthetic'),
('Education Infographic', 'Visually engaging background for educational content and online learning platforms.', 'Image', 'Education', 'Beginner', 1100, 'https://img.freepik.com/free-photo/diverse-student-group-studying-library_23-2148762512.jpg', false, 'Clean educational workspace with books and a tablet, soft ambient lighting, pastel colors, professional and inviting, high-res'),

-- VIDEO EXAMPLES
('Future City Flythrough', 'Cinematic drone footage of a neon-lit cyberpunk metropolis. Ideal for sci-fi openers.', 'Video', 'Creative', 'Pro', 840, 'https://img.freepik.com/free-photo/futuristic-city-landscape-night_23-2150864381.jpg', true, 'Cinematic drone flythrough of a neon-drenched cyberpunk city at night with floating holographic advertisements and flying cars, Unreal Engine 5 style'),
('Ocean Waves 4K', 'Relaxing high-definition aerial footage of tropical ocean waves. Perfect for meditation apps.', 'Video', 'Social Media', 'Beginner', 4200, 'https://img.freepik.com/free-photo/beautiful-tropical-beach-with-sea-ocean_74190-7566.jpg', false, 'Drone view of crystal clear turquoise ocean waves crashing on white sand, relaxing slow motion, 4k cinematic footage'),
('Modern Office Motion', 'Professional background video for corporate websites and professional LinkedIn headers.', 'Video', 'Business', 'Beginner', 1500, 'https://img.freepik.com/free-photo/modern-office-business-meeting_23-2149151240.jpg', false, 'Subtle motion of a modern glass-walled office with blurred professionals walking, professional lighting, corporate look'),
('Cosmic Journey', 'Epic space travel visual through nebulae and star clusters for creative projects.', 'Video', 'Creative', 'Pro', 720, 'https://img.freepik.com/free-photo/cosmic-landscape-with-stars-nebulae_23-2150731002.jpg', false, 'A journey through a colorful galaxy nebula, stars passing by, deep space aesthetics, interstellar travel style, high quality'),

-- AUDIO EXAMPLES
('The History of Rome', 'Professional narration for educational history series. Clear, deep voice with gravitas.', 'Audio', 'Education', 'Beginner', 2100, 'https://img.freepik.com/free-photo/antique-statue-head-close-up_23-2149102640.jpg', false, 'A deep, authoritative male voice narrating the epic rise and fall of the Roman Empire, clear articulation, professional studio quality'),
('Podcast Intro Jingle', 'Energetic and modern audio intro for tech-focused podcasts. Upbeat and clean.', 'Audio', 'Social Media', 'Beginner', 3400, 'https://img.freepik.com/free-photo/professional-microphone-radio-studio_23-2148795551.jpg', true, 'An upbeat and energetic technology podcast intro jingle with synthesized beats and a clean transition sound'),
('Meditation Zen Voice', 'Soft, soothing female narration for guided meditation and mindfulness sessions.', 'Audio', 'Creative', 'Beginner', 5600, 'https://img.freepik.com/free-photo/woman-meditating-peacefully-nature_23-2148762492.jpg', false, 'Gentle and calming female voice for a 10-minute mindfulness session, slow pacing, soothing tone, high-fidelity audio'),
('Corporate VO Pro', 'Neutral, informative professional narration for business training and announcements.', 'Audio', 'Business', 'Pro', 1800, 'https://img.freepik.com/free-photo/businesswoman-giving-presentation_23-2149151243.jpg', false, 'Clear professional corporate voice-over for a business presentation, confident and steady pacing, studio quality'),

-- 3D EXAMPLES
('Modern Workspace 3D', 'Detailed low-poly 3D model of a minimalist home office. Optimized for web viewers.', '3D', 'Business', 'Pro', 430, 'https://img.freepik.com/free-photo/minimalist-desk-with-laptop-plant_23-2149313932.jpg', false, 'A minimalist low-poly 3d model of a modern home office desk with a laptop, lamp, and small plant, soft lighting, 3D printable'),
('AI Assistant UI Kit', '3D UI elements for modern AI application interfaces. Glowing nodes and paths.', '3D', 'Business', 'Pro', 670, 'https://img.freepik.com/free-photo/abstract-futuristic-ai-technology-circuit_23-2150731011.jpg', true, 'A set of glowing 3D UI nodes and interconnected paths for an AI assistant dashboard, futuristic aesthetic'),
('Abstract Sculpture', 'Futuristic organic 3D sculpture for use in digital art and creative web design.', '3D', 'Creative', 'Pro', 310, 'https://img.freepik.com/free-photo/abstract-3d-geometric-sculpture_23-2151044390.jpg', false, 'An abstract fluid 3D sculpture, chrome finish, reflecting colorful lights, organic shapes, high detail, glTF format'),
('Smart Home Hub', '3D model of a modern smart home assistant device with interactive touch interface.', '3D', 'Marketing', 'Beginner', 1200, 'https://img.freepik.com/free-photo/smart-home-assistant-device-table_23-2149102651.jpg', false, '3D model of a sleek smart home speaker with a glowing LED ring and touchscreen display, modern minimalist design, product rendering');
