import StickyTabs from '@/components/ui/sticky-section-tabs'
import { FileTextIcon, ScaleIcon, ShieldAlertIcon, CreditCardIcon, HandshakeIcon } from 'lucide-react'

export const metadata = {
    title: 'Terms of Service - Rive AI',
    description: 'Review the rules and guidelines for using our platform.',
}

export default function TermsOfServicePage() {
    return (
        <div className="max-w-5xl mx-auto fade-in pb-20">
            {/* Page Header */}
            <div className="mb-12">
                <h1 className="text-2xl font-semibold text-zinc-100 mb-1 flex items-center gap-2">
                    <FileTextIcon className="w-6 h-6 text-indigo-400" />
                    Terms of Service
                </h1>
                <p className="text-sm text-zinc-400">
                    Last updated: March 5, 2026. Please read these terms carefully.
                </p>
            </div>

            <div className="relative rounded-2xl border border-white/5 bg-zinc-900/40 overflow-visible backdrop-blur-xl">
                <StickyTabs mainNavHeight="4rem">
                    <StickyTabs.Item title="1. Acceptance of Terms" id="acceptance">
                        <div className="space-y-6">
                            <p>
                                By accessing or using Rive AI, you agree to be bound by these Terms of Service and all applicable laws and regulations.
                            </p>
                            <div className="p-5 rounded-2xl bg-indigo-500/5 border border-indigo-500/10 flex items-start gap-4">
                                <HandshakeIcon className="w-6 h-6 text-indigo-400 shrink-0" />
                                <p className="text-sm leading-relaxed text-zinc-400">
                                    If you do not agree with any of these terms, you are prohibited from using or accessing this site. The materials contained in this website are protected by applicable copyright and trademark law.
                                </p>
                            </div>
                        </div>
                    </StickyTabs.Item>

                    <StickyTabs.Item title="2. Use License" id="license">
                        <div className="space-y-6">
                            <p>Permission is granted to use Rive AI tools for personal or commercial creative projects:</p>
                            <ul className="list-disc pl-5 space-y-3">
                                <li>You own the outputs generated by our AI tools based on your prompts.</li>
                                <li>You may not use the services to generate illegal, harmful, or exploitative content.</li>
                                <li>You may not attempt to decompile or reverse engineer any software contained on Rive AI.</li>
                                <li>This license shall automatically terminate if you violate any of these restrictions.</li>
                            </ul>
                        </div>
                    </StickyTabs.Item>

                    <StickyTabs.Item title="3. Credit System & Payments" id="payments">
                        <div className="space-y-6">
                            <div className="flex items-center gap-3 mb-4 text-white">
                                <CreditCardIcon className="w-6 h-6 text-indigo-400" />
                                <h3 className="text-lg font-medium">Clear & Simple Billing</h3>
                            </div>
                            <ul className="list-disc pl-5 space-y-3">
                                <li><strong>Pay As You Go:</strong> Credits are purchased upfront and used as you generate content.</li>
                                <li><strong>Expiration:</strong> Credits typically do not expire unless your account is inactive for more than 12 months.</li>
                                <li><strong>Refunds:</strong> Credit purchases are non-refundable once any portion of the credits from that purchase has been used.</li>
                            </ul>
                        </div>
                    </StickyTabs.Item>

                    <StickyTabs.Item title="4. Limitation of Liability" id="liability">
                        <div className="space-y-6">
                            <p>
                                Rive AI and its suppliers shall not be held liable for any damages arising out of the use or inability to use the services.
                            </p>
                            <div className="p-5 rounded-2xl bg-red-500/5 border border-red-500/10 flex items-start gap-4">
                                <ShieldAlertIcon className="w-6 h-6 text-red-400 shrink-0" />
                                <div className="text-sm">
                                    <h4 className="font-semibold text-white mb-1 uppercase tracking-wider text-xs">Important Notice</h4>
                                    <p className="opacity-80">AI-generated content may be inaccurate or unexpected. Users are responsible for verifying the suitability of generated outputs for their intended use.</p>
                                </div>
                            </div>
                        </div>
                    </StickyTabs.Item>

                    <StickyTabs.Item title="5. Governing Law" id="law">
                        <div className="space-y-6">
                            <div className="flex items-center gap-3 mb-2 text-white">
                                <ScaleIcon className="w-6 h-6 text-indigo-400" />
                                <h3 className="text-lg font-medium">Jurisdiction</h3>
                            </div>
                            <p>
                                Any claim relating to Rive AI shall be governed by the laws of the jurisdiction in which the company is headquartered without regard to its conflict of law provisions.
                            </p>
                            <p className="pt-8 text-center text-xs text-zinc-500">
                                © 2026 Rive AI. All rights reserved.
                            </p>
                        </div>
                    </StickyTabs.Item>
                </StickyTabs>
            </div>
        </div>
    )
}
