// Import the Supabase server client and the Replicate SDK.
import { createClient } from '@/utils/supabase/server'
import Replicate from 'replicate'

// Set the runtime to 'nodejs' to handle binary image data and large buffers.
export const runtime = 'nodejs'

// Specify the state-of-the-art image model to be used (Google's Imagen-4).
const REPLICATE_MODEL = 'google/imagen-4'

// Initialize the Replicate client with the API token.
const replicate = new Replicate({
    auth: process.env.REPLICATE_API_TOKEN!,
})

// Main POST handler for high-end image generation.
export async function POST(req: Request) {
    const supabase = await createClient()

    // Validate the API token availability.
    if (!process.env.REPLICATE_API_TOKEN) {
        return new Response(JSON.stringify({ error: 'Missing REPLICATE_API_TOKEN' }), {
            status: 500,
            headers: { 'Content-Type': 'application/json' },
        })
    }

    // Authenticate the user session.
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) {
        return new Response('Unauthorized', { status: 401 })
    }

    // Deduct 10 credits for using the high-end Image Generator tool.
    const { data: success, error: rpcError } = await supabase.rpc('deduct_credits', {
        charge_amount: 10,
        tool_name: 'Image Generator'
    })

    if (rpcError) {
        return new Response(rpcError.message, { status: 500 })
    }
    
    // Check if the deduction was successful (sufficient balance).
    if (!success) {
        return new Response('Insufficient credits', { status: 402 })
    }

    // Extract the prompt from the request body.
    const { prompt } = await req.json()
    if (!prompt || typeof prompt !== 'string') {
        return new Response('Missing prompt', { status: 400 })
    }

    try {
        // Trigger the image generation task on Replicate's servers.
        const output = await replicate.run(REPLICATE_MODEL, {
            input: { prompt },
        })

        // Capture the primary output generated by the model.
        const firstOutput = Array.isArray(output) ? output[0] : output

        if (!firstOutput) {
            return new Response(JSON.stringify({ error: 'No image returned from model' }), {
                status: 502,
                headers: { 'Content-Type': 'application/json' },
            })
        }

        let base64: string

        // Logic to extract binary image data from the Replicate output objects.
        if (typeof firstOutput === 'object' && firstOutput !== null) {
            const fileOutput = firstOutput as { blob?: () => Promise<Blob>; url?: () => string; arrayBuffer?: () => Promise<ArrayBuffer> }

            // Extract via Blob stream.
            if (typeof fileOutput.blob === 'function') {
                const blob = await fileOutput.blob()
                const arrayBuffer = await blob.arrayBuffer()
                base64 = Buffer.from(arrayBuffer).toString('base64')
            } 
            // Extract via direct ArrayBuffer.
            else if (typeof fileOutput.arrayBuffer === 'function') {
                const arrayBuffer = await fileOutput.arrayBuffer()
                base64 = Buffer.from(arrayBuffer).toString('base64')
            } 
            // Fetch via temporary URL if direct extraction isn't supported.
            else if (typeof fileOutput.url === 'function') {
                const imageRes = await fetch(fileOutput.url())
                base64 = Buffer.from(await imageRes.arrayBuffer()).toString('base64')
            } else {
                return new Response(JSON.stringify({ error: 'Unsupported output type from model' }), {
                    status: 502,
                    headers: { 'Content-Type': 'application/json' },
                })
            }
        } 
        // Fallback for when the model returns a simple URL string.
        else if (typeof firstOutput === 'string') {
            const imageRes = await fetch(firstOutput)
            if (!imageRes.ok) {
                return new Response(JSON.stringify({ error: 'Failed to fetch generated image' }), {
                    status: 502,
                    headers: { 'Content-Type': 'application/json' },
                })
            }
            base64 = Buffer.from(await imageRes.arrayBuffer()).toString('base64')
        } else {
            return new Response(JSON.stringify({ error: 'Unexpected output format from model' }), {
                status: 502,
                headers: { 'Content-Type': 'application/json' },
            })
        }

        // Return the final image data to the frontend in JSON format.
        return new Response(JSON.stringify({ image: base64 }), {
            headers: { 'Content-Type': 'application/json' },
        })
    } catch (err) {
        // Error logging and handling.
        console.error('Image generation exception', err)
        const message = err instanceof Error ? err.message : 'Image generation error'
        return new Response(JSON.stringify({ error: message }), {
            status: 500,
            headers: { 'Content-Type': 'application/json' },
        })
    }
}